name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC to runs every 7-8 min set cron to '*/1 * * * *'
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create file and commit random times
        run: |
          FILE="commit_number.md"
          
          # Generate a random number between 1 and 5 
          RANDOM_COMMIT_COUNT=$((RANDOM % 5 + 1 )) # Random number between 1 and 5
          echo "Total commits to be made: $(RANDOM_COMMIT_COUNT)"
         
          # Loop to commit the file random number between 1 and 5
          for i in $(seq 1 $RANDOM_COMMIT_COUNT)
          do
            if [ ! -f "FILE" ]; then
              echo "Hello my name is Sajid377" > "$FILE"
              echo "commit no : 1" >> "$FILE"
            else
              CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
              if [ -z "$CURRENT_COUNT" ]; then
                CURRENT_COUNT = 0
              fi
              NEXT_COUNT=$((CURRENT_COUNT + 1))
              sed  -i "/commit number: $NEXT_COUNT" "$FILE"
            fi
            git config --global user.name "sajid377"
            git config --global user.email "sajid.dev90@gmail.com"
            git add "$FILE"
            git commit -m "workflow commit #$i"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sajid377/Test.git
          done
        env:
          GITHUB_TOKEN: ${{secrets.AUTO_COMMIT_TOKEN }}
